### ISSUE TITLE
Error in option file: /home/rtorrent/rtorrent/config.d/00-main.rc:17: Bad return code.

### ISSUE THREAD

**Issue by diogoaguiar** [TuxMeaLux/alpine-rtorrent#5]
I tried launching the image but I'm getting this error:
```
Error in option file: /home/rtorrent/rtorrent/config.d/00-main.rc:17: Bad return code.
```

I 'm using this docker-compose configuration to launch the container:
```
version: '3.7'

services:
    rtorrent:
        image: tuxmealux/alpine-rtorrent
        container_name: rtorrent
        restart: unless-stopped
        ports:
            - "50000:50000"
            - "6881:6881"
            - "6881:6881/udp"
        expose:
            - "16891"
        volumes:
            - /media/sda1/.rtorrent/download:/home/rtorrent/rtorrent/download
            - /media/sda1/.rtorrent/watch:/home/rtorrent/rtorrent/watch
            - /media/sda1/.rtorrent/.session:/home/rtorrent/rtorrent/.session
```

I also tried compiling the image myself, but got the same result.
Any ideas why this is happening?
Thanks.
